# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

env:
  FILE_PATH: '.env/development.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      # Runs a single command using the runners shell
      - name: Send greeting
        run: | 
          echo pwd
          echo "${{ secrets.JSON }}" | base64 --decode >> ${{ env.FILE_PATH }}
      - name: AAAAA
        run: cat ${{ env.FILE_PATH }} | jq

